noa-harvester/README.md
noa-harvester/config/config_test_copernicus.json
noa-harvester/noaharvester/providers/copernicus.py
noa-harvester/pyproject.toml

19 fix some windows issues

---

noa-harvester/CHANGELOG.md
noa-harvester/README.md
noa-harvester/config/config_test_earthsearch.json
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/providers/earthsearch.py
noa-harvester/tests/conftest.py
noa-harvester/tests/test_providers.py

27 introduce asset selection in earthsearch

---

noa-harvester/noaharvester/cli.py
noa-harvester/noaharvester/harvester.py
noa-harvester/noaharvester/utils.py
noa-harvester/tests/test_utils.py

All in one

---

.gitignore
noa-harvester/README.md
noa-postprocess-aggregate/CHANGELOG.md
noa-postprocess-aggregate/Dockerfile
noa-postprocess-aggregate/docker-compose.yml
noa-postprocess-aggregate/noapostaggregate/__init__.py
noa-postprocess-aggregate/noapostaggregate/cli.py
noa-postprocess-aggregate/noapostaggregate/postaggregate.py
noa-postprocess-aggregate/pyproject.toml
noa-postprocess-aggregate/requirements.txt
noa-preprocess/config/default_clip.json

33 postprocess aggregate

---

noa-postprocess-aggregate/noapostaggregate/postaggregate.py

44 postprocessing histogram should take the earliest reference

---

noa-harvester/CHANGELOG.md
noa-harvester/README.md
noa-harvester/noaharvester/cli.py
noa-harvester/noaharvester/harvester.py
noa-harvester/noaharvester/providers/__init__.py
noa-harvester/noaharvester/providers/copernicus.py
noa-harvester/noaharvester/providers/earthdata.py
noa-harvester/noaharvester/providers/earthsearch.py
noa-harvester/tests/conftest.py
noa-harvester/tests/test_harvester.py
noa-harvester/tests/test_providers.py
noa-harvester/tests/test_utils.py
noa-postprocess-aggregate/noapostaggregate/cli.py
noa-postprocess-aggregate/noapostaggregate/postaggregate.py
noa-preprocess/noapreprocess/preprocess.py

32 optional download location for harvester

---

noa-preprocess/CHANGELOG.md
noa-preprocess/README.md
noa-preprocess/config/unzip_s3.json
noa-preprocess/noapreprocess/preprocess.py

Closes #55 
Generic zip extraction

Generic extract to facilitate Sentinel 3 archives

---

noa-preprocess/CHANGELOG.md
noa-preprocess/config/default_clip.json
noa-preprocess/noapreprocess/__init__.py
noa-preprocess/noapreprocess/cli.py
noa-preprocess/noapreprocess/preprocess.py

58 pre recursive clip search same folder option

---

noa-preprocess/CHANGELOG.md
noa-preprocess/README.md
noa-preprocess/noapreprocess/cli.py
noa-preprocess/noapreprocess/preprocess.py

47 pre clip store to clipped folder under output

---

noa-postprocess-aggregate/noapostaggregate/cli.py
noa-postprocess-aggregate/noapostaggregate/postaggregate.py
noa-preprocess/config/default_clip.json
noa-preprocess/noapreprocess/cli.py

Generalized histogram matching, not fully dif vector though: currently only works well for per month results. Needs follow up

61 post generalize operations for sentinel 2

---

noa-harvester/CHANGELOG.md
noa-harvester/Dockerfile
noa-harvester/README.md
noa-harvester/config/config_from_uri.json
noa-harvester/docker-compose.yml
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/cli.py
noa-harvester/noaharvester/db/database.ini
noa-harvester/noaharvester/db/utils.py
noa-harvester/noaharvester/harvester.py
noa-harvester/noaharvester/providers/__init__.py
noa-harvester/noaharvester/providers/copernicus.py
noa-harvester/noaharvester/providers/earthdata.py
noa-harvester/noaharvester/providers/earthsearch.py
noa-harvester/pyproject.toml
noa-harvester/requirements.txt
noa-harvester/tests/test_providers.py

67 poc harvester cli for gateway

---

noa-harvester/Dockerfile
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/Dockerfile
noa-stac-ingest/README.md
noa-stac-ingest/config/default_config.json
noa-stac-ingest/config/test_config.json
noa-stac-ingest/docker-compose.yml
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/_create_catalog.py
noa-stac-ingest/noastacingest/_create_collection.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/db/database.ini
noa-stac-ingest/noastacingest/db/utils.py
noa-stac-ingest/noastacingest/ingest.py
noa-stac-ingest/noastacingest/messaging/__init__.py
noa-stac-ingest/noastacingest/messaging/kafka_consumer.py
noa-stac-ingest/noastacingest/messaging/kafka_producer.py
noa-stac-ingest/noastacingest/messaging/message.py
noa-stac-ingest/noastacingest/utils.py
noa-stac-ingest/pyproject.toml
noa-stac-ingest/requirements.txt

Closes #53 
Version 0.2.0. Has kafka interface, pgstac for uuid path information, and STAC ingestion (pgstac)

53 noa stac ingest

---

noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/noastacingest/ingest.py

Closes #80 
Under ["properties"]["noa_product_id"]

80 noastacingest introduce provider and UUID in properties of new items

---

noa-harvester/CHANGELOG.md
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/cli.py
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/cli.py

82 bug kafka consumer or topics

---

noa-harvester/CHANGELOG.md
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/harvester.py
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/ingest.py

84 harvester bug on extracting UUID title from db

---

noa-harvester/CHANGELOG.md
noa-harvester/config/config_service.json
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/cli.py
noa-harvester/noaharvester/harvester.py
noa-harvester/noaharvester/messaging/kafka_consumer.py
noa-harvester/noaharvester/messaging/message.py
noa-harvester/noaharvester/utils.py
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/config/config_service.json
noa-stac-ingest/config/default_config.json
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/ingest.py
noa-stac-ingest/noastacingest/messaging/kafka_consumer.py
noa-stac-ingest/noastacingest/messaging/message.py
noa-stac-ingest/noastacingest/utils.py

90 harvester bug kafka topics

---

noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/Dockerfile
noa-stac-ingest/docker-compose.yml
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/ingest.py

92 stac ingest bug and stac db credentials

---

noa-harvester/CHANGELOG.md
noa-harvester/README.md
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/harvester.py
noa-harvester/noaharvester/providers/copernicus.py

96 harvester credentials fallback

---

noa-harvester/CHANGELOG.md
noa-harvester/noaharvester/__init__.py
noa-harvester/noaharvester/cli.py
noa-harvester/noaharvester/harvester.py

Added log messages and sending single output message when list completes

---

noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/Dockerfile
noa-stac-ingest/README.md
noa-stac-ingest/docker-compose.yml
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/ingest.py

102 refactor stacingest

---

noa-stac-ingest/README.md
noa-stac-ingest/config/config_service.json
noa-stac-ingest/config/init_catalog.json
noa-stac-ingest/config/init_collection.json
noa-stac-ingest/noastacingest/_create_catalog.py
noa-stac-ingest/noastacingest/_create_collection.py
noa-stac-ingest/noastacingest/ingest.py

106 noastacingest documentation corrections

---

noa-ui/browser/views.py

This PR fixes the connection with the gateway so to use the harvester processor for getting the requested metadata. This metadata is served to the UI.

Hotfix: Fix noisy comments that break the connection to the gateway

---

noa-harvester/Dockerfile
noa-harvester/docker-compose.yml
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/Dockerfile
noa-stac-ingest/docker-compose.yml
noa-stac-ingest/noastacingest/ingest.py

111 hotfix on default directories

---

noa-harvester/config/config_sentinel_2.json
noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/_create_collection.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/ingest.py

Some logging additions mainly on STAC Ingest.
Also, fail if no kafka topics are found when launcing

42 refactor processors for quality

---

noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/config/init_catalog_dev.json
noa-stac-ingest/config/init_collection_dev.json
noa-stac-ingest/config/test_config.json
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/ingest.py

118 harvester   bug on sentinel 1 ingestion

---

noa-preprocess/CHANGELOG.md
noa-preprocess/noapreprocess/__init__.py
noa-preprocess/noapreprocess/cli.py
noa-preprocess/noapreprocess/preprocess.py

122 preprocessing no qi rasters

---

noa-change-detection-mapping/noachdm/cli.py
noa-change-detection-mapping/noachdm/messaging/message.py
noa-change-detection-mapping/noachdm/utils.py

Pure python solution

---

noa-change-detection-mapping/CHANGELOG.md
noa-change-detection-mapping/docker-compose.yml
noa-change-detection-mapping/noachdm/__init__.py
noa-change-detection-mapping/noachdm/chdm.py
noa-change-detection-mapping/noachdm/utils.py

Hotfix, early catch of aonther bug, log fixes and Changelog

---

noa-change-detection-mapping/CHANGELOG.md
noa-change-detection-mapping/noachdm/__init__.py
noa-change-detection-mapping/noachdm/chdm.py
noa-change-detection-mapping/noachdm/cli.py
noa-change-detection-mapping/noachdm/utils.py
noa-change-detection-mapping/pyproject.toml
noa-change-detection-mapping/requirements.txt

146 chdm hotfix for rasterio bug

---

noa-change-detection-mapping/CHANGELOG.md
noa-change-detection-mapping/noachdm/__init__.py
noa-change-detection-mapping/noachdm/chdm.py
noa-change-detection-mapping/noachdm/cli.py
noa-change-detection-mapping/noachdm/utils.py

156 chdm sum up all errors

---

noa-change-detection-mapping/CHANGELOG.md
noa-change-detection-mapping/noachdm/__init__.py
noa-change-detection-mapping/noachdm/chdm.py
noa-change-detection-mapping/noachdm/cli.py
noa-change-detection-mapping/noachdm/messaging/__init__.py
noa-change-detection-mapping/noachdm/messaging/kafka_consumer.py
noa-change-detection-mapping/noachdm/messaging/kafka_producer.py
noa-change-detection-mapping/noachdm/messaging/message.py
noa-change-detection-mapping/noachdm/models/BIT.py
noa-change-detection-mapping/noachdm/utils.py

158 chdm cannot write file in docker

---

noa-stac-ingest/CHANGELOG.md
noa-stac-ingest/Dockerfile
noa-stac-ingest/README.md
noa-stac-ingest/config/config_service_s3.json
noa-stac-ingest/noastacingest/__init__.py
noa-stac-ingest/noastacingest/_create_collection.py
noa-stac-ingest/noastacingest/cli.py
noa-stac-ingest/noastacingest/create_item_beyond.py
noa-stac-ingest/noastacingest/create_item_copernicus.py
noa-stac-ingest/noastacingest/db/utils.py
noa-stac-ingest/noastacingest/ingest.py
noa-stac-ingest/noastacingest/messaging/__init__.py
noa-stac-ingest/noastacingest/messaging/kafka_consumer.py
noa-stac-ingest/noastacingest/messaging/kafka_producer.py
noa-stac-ingest/noastacingest/messaging/message.py
noa-stac-ingest/noastacingest/utils.py
noa-stac-ingest/pyproject.toml
noa-stac-ingest/requirements.txt

Closes #143 
Ingests items from s3 buckets, populates STAC Items and Collections which reside in s3 buckets

143 stacingest chdm from and to s3
